<?php

/**
 * Implements hook_menu().
 */
function students_menu() {
  $items['admin/config/content/students-config'] = array(
    'title' => 'Students Config Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('students_admin_settings'),
    'access arguments' => array('access students content'),
    'file' => 'includes/students.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['add-students'] = array(
    'title' => 'Add student',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('students_edit_settings'),
    'access arguments' => array('edit students content'),
    'file' => 'includes/node.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['students'] = array(
    'title' => 'Students page',
    'page callback' => 'main_table',
    'access arguments' => array('access students content'),
    //'file' => 'includes/theme.table.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function students_permission() {
  return array(
    'access students content' => array(
      'title' => t('Administer Students content'),
      'description' => t('Perform administration tasks for Students module.'),
    ),
    'edit students content' => array(
      'title' => t('Edit Students content'),
      'description' => t('Perform administration tasks for Students module.'),
    ),
    'delete students content' => array(
      'title' => t('Delete Students content'),
      'description' => t('Perform administration tasks for Students module.'),
    ),
  );
}

function main_table($variables) {
  // Table header
  $table_header = array(
    // Column 1
    'id' => array(
      'data' => 'id',
      'class' => 'col-id',
    ),
    // Column 2
    'name' => array(
      'data' => t('Name'),
      'class' => 'col-name',
    ),
    // Column 3
    'faculty' => array(
      'data' => t('Faculty Number'),
      'class' => 'col-number',
    ),
    // Column 3
    'gender' => array(
      'data' => t('Students gender'),
      'class' => 'col-gender',
    ),
  );
  // Table rows
  $sql = "SELECT id, name, faculty, gender FROM {students}";
  $res = db_query($sql);
  $table_rows = array();
  while ($row = db_fetch_object($res)) {
    $table_rows[] = array(
      'id' => array(
        // Column 1
        'id' => array(
          'data' => $row->id,
          'class' => 'col-id',
        ),
        // Column 2
        'name' => array(
          'data' => l($row->name, 'students/' . $row->id),
          'class' => 'col-name',
        ),
        // Column 3
        'faculty' => array(
          'data' => l($row->faculty, 'students/' . $row->faculty),
          'class' => 'col-faculty',
        ),
      ),
      // Row attributes
      'id' => 'students-row-' . $row->id,
      'class' => 'students-row',
    );
  }
  // Format and print out the table.
  return theme('table', array(
    'header' => $table_header,
    'rows' => $table_rows,
    'id' => 'table-articles',
    'class' => 'students',
  ));
}
